### ISSUE TITLE
apg to fasta 

### ISSUE THREAD

**Issue by Rhia15** [sanger-tol/agp-tpf-utils#1]
Hi, this is a great tool! I have managed to manually curate my map, however, I was was using the pretext_to_tpf.py script to convert my APG file into a fasta file and got this error. 

Traceback (most recent call last):
  File "/gpfs01/home/mbars7/yahs/pyrenaica_hap1/agp-tpf-utils/src/tola/assembly/scripts/pretext_to_tpf.py", line 244, in <module>
    cli()
  File "/gpfs01/home/mbars7/miniconda3/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs01/home/mbars7/miniconda3/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/gpfs01/home/mbars7/miniconda3/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs01/home/mbars7/miniconda3/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs01/home/mbars7/yahs/pyrenaica_hap1/agp-tpf-utils/src/tola/assembly/scripts/pretext_to_tpf.py", line 149, in cli
    build_asm.remap_to_input_assembly(prtxt_asm, input_asm)
  File "/gpfs01/home/mbars7/yahs/pyrenaica_hap1/agp-tpf-utils/src/tola/assembly/build_assembly.py", line 74, in remap_to_input_assembly
    self.cut_remaining_overhangs()
  File "/gpfs01/home/mbars7/yahs/pyrenaica_hap1/agp-tpf-utils/src/tola/assembly/build_assembly.py", line 123, in cut_remaining_overhangs
    self.cut_fragments(fnd)
  File "/gpfs01/home/mbars7/yahs/pyrenaica_hap1/agp-tpf-utils/src/tola/assembly/build_assembly.py", line 143, in cut_fragments
    self.qc_sub_fragments(fnd, sub_fragments)
  File "/gpfs01/home/mbars7/yahs/pyrenaica_hap1/agp-tpf-utils/src/tola/assembly/build_assembly.py", line 187, in qc_sub_fragments
    raise ValueError(msg)
ValueError: Sum of fragment lengths 4_694_157 does not match orginal fragment length 4_707_000
Expecting 1 abutting sub fragments but got 0

I used the TPF file I generated before the manual curation and the apg file generated after, I was just wondering what it means by different fragment lengths? I am not sure where the fragments could have gone? 

Thank you very much.

**Comment by jgrg** [comment]
Did you fix it? If not, we can help you track down the problem scaffold.

**Comment by Rhia15** [comment]
Hi, thank you for such a quick response, I managed to fix it the first time and realised that I didn't flood fill my chromosomes. But I made some more rearrangements after and flood filled it to make sure all the scaffolds were included the second time, but I am still receiving the same error, so I'm not quite sure what's causing it. 

This is the error on the second run. 

Traceback (most recent call last):
  File "/gpfs01/home/mbars7/yahs/pyrenaica_hap1/agp-tpf-utils/src/tola/assembly/scripts/pretext_to_tpf.py", line 244, in <module>
    cli()
  File "/gpfs01/home/mbars7/miniconda3/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs01/home/mbars7/miniconda3/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/gpfs01/home/mbars7/miniconda3/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs01/home/mbars7/miniconda3/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs01/home/mbars7/yahs/pyrenaica_hap1/agp-tpf-utils/src/tola/assembly/scripts/pretext_to_tpf.py", line 149, in cli
    build_asm.remap_to_input_assembly(prtxt_asm, input_asm)
  File "/gpfs01/home/mbars7/yahs/pyrenaica_hap1/agp-tpf-utils/src/tola/assembly/build_assembly.py", line 74, in remap_to_input_assembly
    self.cut_remaining_overhangs()
  File "/gpfs01/home/mbars7/yahs/pyrenaica_hap1/agp-tpf-utils/src/tola/assembly/build_assembly.py", line 123, in cut_remaining_overhangs
    self.cut_fragments(fnd)
  File "/gpfs01/home/mbars7/yahs/pyrenaica_hap1/agp-tpf-utils/src/tola/assembly/build_assembly.py", line 143, in cut_fragments
    self.qc_sub_fragments(fnd, sub_fragments)
  File "/gpfs01/home/mbars7/yahs/pyrenaica_hap1/agp-tpf-utils/src/tola/assembly/build_assembly.py", line 187, in qc_sub_fragments
    raise ValueError(msg)
ValueError: Sum of fragment lengths 4_694_157 does not match orginal fragment length 4_707_000
Expecting 1 abutting sub fragments but got 0

And I have attached the agp file used. Do let me know if you need to see any other file. Any help would be really appreciated. 

Thank you so much :) 
[6_8.3_flod2_pyrenaica_hap1_gap_telomere_gfa.pretext.agp.txt](https://github.com/user-attachments/files/16540352/6_8.3_flod2_pyrenaica_hap1_gap_telomere_gfa.pretext.agp.txt)

**Comment by Rhia15** [comment]
Sorry, I also found that the "original fragment length" of 4_707_000 relates to scaffold 17 in my TPF file, which also makes up scaffold 5 in my AGP file, do scaffolds have to remain intact? Is this because I split up scaffold 17? Can I ask how the sum of the fragments is calculated as I added up the fragments in scaffold 5 and scaffold 17 separately and it doesn't add up to 4_694_157? So just wondering how it calculated 4_694_157. Thank you!

**Comment by jgrg** [comment]
OK, so running the `asm-format` script on your file, to generate the `STR` output format I find useful for debugging:
```sh
asm-format -f STR 6_8.3_flod2_pyrenaica_hap1_gap_telomere_gfa.pretext.agp.txt | less
```

I can see that there is a small 12,843 bp long fragment of `scaffold_17` in `Scaffold_2`, your second chromosome in PretextView:
```
  Scaffold_2
           115_591  scaffold_2:1-115591(+) Painted
               100  Gap:100 scaffold
            12_843  scaffold_17:64218-77060(+) Painted
               100  Gap:100 scaffold
            64_217  scaffold_6:11828855-11893071(+) Painted
               100  Gap:100 scaffold
        11_764_637  scaffold_6:64218-11828854(-) Painted
               100  Gap:100 scaffold
        22_810_037  scaffold_3:1-22810037(+) Painted
               100  Gap:100 scaffold
         1_053_167  scaffold_39:25687-1078853(-) Painted
               100  Gap:100 scaffold
         5_985_066  scaffold_6:12072881-18057946(-) Painted
               100  Gap:100 scaffold
            38_531  scaffold_6:18057947-18096477(-) Painted
               100  Gap:100 scaffold
           179_809  scaffold_6:11893072-12072880(+) Painted
               100  Gap:100 scaffold
         2_645_759  scaffold_23:102748-2748506(+) Painted
```

Since it is only 1 pixel long, it is assumed to be a mistake and is discarded. You somehow need to adjust the boundaries of the rearrangement so that this pixel is moved to the end of one of the two other pieces of `scaffold_17` found in `Scaffold_5` or `Scaffold_8`. If you have difficulty doing this I can get one of our curators to give you some hints.

**Comment by Rhia15** [comment]
Thank you very much, this was really helpful, I will remove these 1 pixel long fragments and see if it works :)

**Comment by Rhia15** [comment]
Hi, sorry I had to reopen this, I have tried to take out these one pixel fragments from all my painted scaffolds, I re ran the asm_format.py script on my new agp file to recheck everything. I found no 1 pixel fragments in any of my new painted scaffolds, however I am still getting the same error. I'm wondering if all the fragments of one scaffold have to stay together? as scaffold 17 in chromosome 5 appears to be problematic but i'm not sure why as it's quite a large fragment? 

Just incase, this is the new AGP file with the 1 pixel fragments removed. 

[6_8.5_flod2_pyrenaica_hap1_gap_telomere_gfa.pretext.txt](https://github.com/user-attachments/files/16579573/6_8.5_flod2_pyrenaica_hap1_gap_telomere_gfa.pretext.txt)

Thank you!

**Comment by Rhia15** [comment]
Hi, Thank you for your reply! By "removed" I meant moving it to the end of the assembly where all the debris was, so it's not included in the painted scaffolds. I'm just wondering, how does this work if fragments in the "debris" section are equivalent to 1 pixel? Would I need to get rid of these in the original fasta file beforehand? 

Thank you!

**Comment by jgrg** [comment]
Any small fragments missing from the PretextView AGP will be rescued and added to the unplaced "debris" scaffolds.
This doesn't happen to your single pixel fragment of `scaffold_17` because it is part of a cut scaffold.

**Comment by Rhia15** [comment]
Hi, thank you this worked great :)
